"""Conan recipe for Apache brpc 1.11.0 (local, not on Conan Center).

brpc is not published on Conan Center Index, so we maintain this local recipe.
It downloads brpc 1.11.0 source from GitHub and builds it with CMake, pointing
all dependency paths at Conan packages to avoid picking up Homebrew or system
libraries.

Why brpc 1.11.0
---------------
brpc 1.11.0 is the latest release that works with protobuf 3.x (the 3.21.12
series).  Newer protobuf versions (4.x+, rebranded as "protobuf" from
"google-protobuf") require abseil and C++17.  braft — and by extension
QuorumKit — uses ``google::protobuf::Closure``, which was removed in protobuf
3.22+.  Staying on 3.21.12 is mandatory until those call sites are migrated.

Why no CMakeDeps
----------------
brpc's CMakeLists.txt uses raw ``find_path``/``find_library`` calls (not modern
``find_package`` with CONFIG mode) for most dependencies.  Conan's CMakeDeps
generator produces config-mode ``.cmake`` files that conflict with brpc's
custom Find modules — in particular, the generated ``protobuf-config.cmake``
sets imported-target properties that break brpc's ``CompileProto.cmake``,
which expects plain variables like ``PROTOBUF_PROTOC_EXECUTABLE``.

Instead, we append ``CACHE FORCE`` variable assignments directly to the Conan
toolchain file (``conan_toolchain.cmake``).  The toolchain loads before any
``CMakeLists.txt`` code, so the CACHE values are set before
``find_path``/``find_library``/``find_package`` execute.  Those commands check
the cache first and become no-ops when they see the variable is already set.

The Homebrew contamination problem
-----------------------------------
On macOS, Apple Clang adds ``/opt/homebrew/include`` to the system include
search path.  If Homebrew protobuf (v5/v7) is installed, its headers shadow
Conan's protobuf 3.21.12 headers, causing "generated by newer protoc" version
mismatch errors at compile time.  We fix this three ways:

1. ``include_directories(BEFORE ...)`` (without SYSTEM) in the toolchain to
   prepend Conan include paths as ``-I`` flags before all others.  The SYSTEM
   keyword is intentionally omitted — ``-isystem`` paths are always searched
   AFTER ``-I`` paths, so ``-isystem`` cannot override a ``-I`` to
   ``/opt/homebrew/include``.  ``BEFORE`` prepends them even before brpc's
   own ``include_directories()`` calls.
2. ``CMAKE_IGNORE_PATH`` / ``CMAKE_IGNORE_PREFIX_PATH`` set in the toolchain
   to prevent all ``find_*`` commands from searching ``/opt/homebrew``.
3. A config-mode shim ``ProtobufConfig.cmake`` in the generators folder
   (see ``_write_protobuf_config_shim``).
4. A module-mode shim ``FindProtobuf.cmake`` in brpc's ``cmake/`` directory
   (see ``_write_find_protobuf_shim``).  Belt-and-suspenders fallback.

Why two shims are needed
~~~~~~~~~~~~~~~~~~~~~~~~
Conan's CMakeToolchain sets ``CMAKE_FIND_PACKAGE_PREFER_CONFIG ON``, which
makes ``find_package(Protobuf)`` search **config mode first** (checking
``CMAKE_PREFIX_PATH`` for ``ProtobufConfig.cmake``).  Module mode
(``CMAKE_MODULE_PATH`` → ``FindProtobuf.cmake``) only runs as a fallback.

Without the config-mode shim, CMake finds Homebrew's
``/opt/homebrew/lib/cmake/protobuf/protobuf-config.cmake`` and uses Homebrew's
protoc v7.x — producing ``.pb.h`` files incompatible with Conan's v3 headers.

The config-mode shim (written to the generators folder, which is first on
``CMAKE_PREFIX_PATH``) intercepts this before Homebrew's config file is found.
The module-mode shim is a safety net in case config mode is somehow bypassed.
"""

import os

from conan import ConanFile
from conan.tools.cmake import CMake, CMakeToolchain, cmake_layout
from conan.tools.files import get, save


class BrpcConan(ConanFile):
    name = "brpc"
    version = "1.11.0"
    license = "Apache-2.0"
    url = "https://github.com/apache/brpc"
    description = "Apache brpc - an industrial-grade RPC framework"
    settings = "os", "compiler", "build_type", "arch"
    options = {
        "shared": [True, False],
        "fPIC": [True, False],
    }
    default_options = {
        "shared": False,
        "fPIC": True,
    }

    def requirements(self):
        # protobuf 3.21.12: last 3.x release before the abseil-requiring
        # rename.  See module docstring for why we pin this version.
        self.requires("protobuf/3.21.12")
        self.requires("gflags/2.2.2")
        self.requires("leveldb/1.23")
        self.requires("openssl/3.4.1")
        self.requires("zlib/1.3.1")

    def build_requirements(self):
        # tool_requires makes protoc available as a build tool.  This is the
        # same version as the library requirement so headers and generated
        # code stay in sync.
        self.tool_requires("protobuf/3.21.12")

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def source(self):
        get(
            self,
            "https://github.com/apache/brpc/archive/refs/tags/1.11.0.tar.gz",
            strip_root=True,
        )
        self._write_find_protobuf_shim()

    def _write_find_protobuf_shim(self):
        """Write a module-mode shim ``FindProtobuf.cmake`` into brpc's ``cmake/``.

        This is the **fallback** shim.  The primary defense against Homebrew
        protobuf contamination is the config-mode shim written by
        ``_write_protobuf_config_shim()`` during ``generate()``.  This
        module-mode shim exists as belt-and-suspenders: if config mode is
        somehow bypassed, ``find_package(Protobuf)`` falls through to module
        mode, finds this file on ``CMAKE_MODULE_PATH``, and returns the
        correct Conan paths instead of invoking CMake's built-in
        ``FindProtobuf.cmake``.

        The shim lives in brpc's ``cmake/`` directory because brpc's
        CMakeLists.txt does ``set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)``
        before calling ``find_package(Protobuf REQUIRED)``.
        """
        shim = """\
# FindProtobuf.cmake — shim installed by QuorumKit's brpc Conan recipe.
#
# Prevents CMake's built-in FindProtobuf from running, which would find
# Homebrew's protoc (v7.x) instead of Conan's protoc (v3.21.12).
# All variables were already CACHE-FORCE-set by conan_toolchain.cmake
# (appended by BrpcConan.generate()).
#
# Variables expected in cache:
#   Protobuf_INCLUDE_DIR / PROTOBUF_INCLUDE_DIR
#   Protobuf_LIBRARY / PROTOBUF_LIBRARY / PROTOBUF_LIBRARIES
#   Protobuf_PROTOC_EXECUTABLE / PROTOBUF_PROTOC_EXECUTABLE
#   Protobuf_PROTOC_LIBRARY / PROTOBUF_PROTOC_LIBRARY

# Declare found — skip all filesystem searching.
set(Protobuf_FOUND TRUE)
set(PROTOBUF_FOUND TRUE)

# 3.21.12 keeps brpc on the C++11 / pre-abseil code path.
# brpc checks: if(Protobuf_VERSION GREATER 4.21) → would trigger abseil/C++17.
set(Protobuf_VERSION "3.21.12")

# Propagate cache vars into the local scope.  CMake cache variables are
# visible everywhere, but some code paths (e.g. brpc's CompileProto.cmake)
# read variables that might have been set() locally by a real FindProtobuf.
# Explicitly setting them here ensures consistent behavior.
set(PROTOBUF_INCLUDE_DIR "${Protobuf_INCLUDE_DIR}")
set(PROTOBUF_INCLUDE_DIRS "${Protobuf_INCLUDE_DIR}")
set(PROTOBUF_LIBRARIES "${Protobuf_LIBRARY}")
set(PROTOBUF_PROTOC_EXECUTABLE "${Protobuf_PROTOC_EXECUTABLE}")

message(STATUS "FindProtobuf shim: protoc at ${Protobuf_PROTOC_EXECUTABLE}")
message(STATUS "FindProtobuf shim: headers at ${Protobuf_INCLUDE_DIR}")
"""
        save(self, os.path.join("cmake", "FindProtobuf.cmake"), shim)

    def _write_protobuf_config_shim(self):
        """Write a config-mode ``ProtobufConfig.cmake`` into the generators folder.

        This is the **primary** defense against Homebrew protobuf contamination.

        Conan's CMakeToolchain sets ``CMAKE_FIND_PACKAGE_PREFER_CONFIG ON``,
        so ``find_package(Protobuf REQUIRED)`` searches config mode first.
        Without this shim, CMake walks ``CMAKE_PREFIX_PATH`` and system paths,
        finds Homebrew's ``/opt/homebrew/lib/cmake/protobuf/protobuf-config.cmake``,
        and sets all protobuf variables (including protoc) to Homebrew v7.x.

        The generators folder is prepended to ``CMAKE_PREFIX_PATH`` by the
        Conan toolchain (before any user CMakeLists.txt runs).  Placing
        ``ProtobufConfig.cmake`` there ensures it is found first in config
        mode — before Homebrew's config file.

        We also CACHE-FORCE ``Protobuf_DIR`` to the generators folder so
        that ``find_package`` checks there explicitly (``Protobuf_DIR`` has
        the highest priority in config-mode search).
        """
        config = """\
# ProtobufConfig.cmake — config-mode shim installed by QuorumKit's brpc
# Conan recipe.
#
# Conan sets CMAKE_FIND_PACKAGE_PREFER_CONFIG=ON, which makes find_package
# search config mode first.  Without this file, CMake finds Homebrew's
# protobuf-config.cmake (protobuf v7.x) and uses the wrong protoc.
#
# This shim intercepts the config-mode search (placed in the generators
# folder, which is first on CMAKE_PREFIX_PATH) and declares Protobuf
# found using variables already CACHE-FORCE-set by conan_toolchain.cmake.

set(Protobuf_FOUND TRUE)
set(PROTOBUF_FOUND TRUE)

# 3.21.12 keeps brpc on the C++11 / pre-abseil code path.
# brpc checks: if(Protobuf_VERSION GREATER 4.21) → would trigger abseil/C++17.
set(Protobuf_VERSION "3.21.12")
set(Protobuf_VERSION_STRING "3.21.12")

# Propagate cache vars into local scope for brpc's CompileProto.cmake.
set(PROTOBUF_INCLUDE_DIR "${Protobuf_INCLUDE_DIR}")
set(PROTOBUF_INCLUDE_DIRS "${Protobuf_INCLUDE_DIR}")
set(PROTOBUF_LIBRARIES "${Protobuf_LIBRARY}")
set(PROTOBUF_PROTOC_EXECUTABLE "${Protobuf_PROTOC_EXECUTABLE}")

message(STATUS "ProtobufConfig shim: protoc at ${Protobuf_PROTOC_EXECUTABLE}")
message(STATUS "ProtobufConfig shim: headers at ${Protobuf_INCLUDE_DIR}")
"""
        config_path = os.path.join(self.generators_folder, "ProtobufConfig.cmake")
        save(self, config_path, config)

    @staticmethod
    def _find_lib(dep_info, name_hint=None):
        """Locate the actual library file for a Conan dependency.

        Conan's ``cpp_info.libs`` contains logical library names (e.g.
        ``gflags_nothreads``), not file paths.  brpc's CMakeLists.txt expects
        full paths in its CACHE variables (e.g. ``GFLAGS_LIBRARY``).  This
        helper resolves the logical name to an absolute path by scanning the
        package's ``libdirs``.

        *name_hint* narrows the search when a package exports multiple libs
        (e.g. protobuf exports ``protobuf``, ``protobuf-lite``, ``protoc``).
        """
        candidates = list(dep_info.libs) if dep_info.libs else []
        if name_hint:
            matching = [n for n in candidates if name_hint in n]
            if matching:
                candidates = matching

        for libdir in dep_info.libdirs:
            for lib_name in candidates:
                for prefix in ("lib", ""):
                    for ext in (".a", ".dylib", ".so", ".lib"):
                        path = os.path.join(libdir, f"{prefix}{lib_name}{ext}")
                        if os.path.isfile(path):
                            return path.replace("\\", "/")

        # Fallback: brute-force scan the libdir.  This catches cases where
        # cpp_info.libs doesn't exactly match the filename (e.g. Conan's
        # gflags 2.2.2 ships as ``libgflags_nothreads.a``).
        if name_hint:
            for libdir in dep_info.libdirs:
                if not os.path.isdir(libdir):
                    continue
                for fname in sorted(os.listdir(libdir)):
                    if name_hint in fname and fname.endswith(
                        (".a", ".dylib", ".so", ".lib")
                    ):
                        return os.path.join(libdir, fname).replace("\\", "/")
        return ""

    def generate(self):
        tc = CMakeToolchain(self)

        # ---------------------------------------------------------------
        # brpc feature flags.
        #
        # These map to CMake options defined at the top of brpc's
        # CMakeLists.txt.  tc.variables puts them into the toolchain as
        # set(VAR VALUE) — they are visible before the project loads.
        # ---------------------------------------------------------------
        tc.variables["WITH_GLOG"] = "OFF"  # We don't use glog
        tc.variables["WITH_THRIFT"] = "OFF"  # No thrift framed protocol
        tc.variables["WITH_MESALINK"] = "OFF"  # No MesaLink TLS
        tc.variables["WITH_BORINGSSL"] = "OFF"  # Use OpenSSL, not BoringSSL
        tc.variables["WITH_RDMA"] = "OFF"  # No RDMA transport
        tc.variables["WITH_SNAPPY"] = "OFF"  # brpc bundles its own snappy in butil
        tc.variables["BUILD_BRPC_TOOLS"] = "OFF"  # Skip rpc_press / rpc_replay
        tc.variables["BUILD_SHARED_LIBS"] = "ON" if self.options.shared else "OFF"
        tc.variables["DOWNLOAD_GTEST"] = "OFF"  # Tests are off anyway

        # brpc's cmake_minimum_required(VERSION 2.8.12) predates CMake 3.5.
        # CMake 3.27+ warns/errors on old minimum versions unless this is set.
        # Ref: https://cmake.org/cmake/help/v3.27/variable/CMAKE_POLICY_VERSION_MINIMUM.html
        tc.cache_variables["CMAKE_POLICY_VERSION_MINIMUM"] = "3.5"

        tc.generate()

        # Write config-mode ProtobufConfig.cmake into the generators folder.
        # Must happen after tc.generate() so the generators folder exists.
        self._write_protobuf_config_shim()

        # ---------------------------------------------------------------
        # Inject Conan dependency paths into the toolchain.
        #
        # Why we append to conan_toolchain.cmake instead of using CMakeDeps:
        # see the module docstring ("Why no CMakeDeps").
        #
        # How this works:
        #   1. CMake loads conan_toolchain.cmake via CMAKE_TOOLCHAIN_FILE
        #      before processing any CMakeLists.txt.
        #   2. Our CACHE FORCE assignments set all the *_INCLUDE_PATH,
        #      *_LIBRARY, and *_EXECUTABLE variables that brpc's
        #      find_path / find_library / find_package calls look for.
        #   3. When those find_* commands run, they see the cache variable
        #      is already set and skip the filesystem search entirely.
        #   4. For Protobuf specifically, the shim FindProtobuf.cmake
        #      (written in source()) also prevents the built-in module
        #      from running — belt and suspenders.
        #
        # We open the file in append mode ("a") because CMakeToolchain
        # already wrote the standard Conan content.  Our additions go
        # at the end, after Conan's own variable declarations.
        # ---------------------------------------------------------------

        gf = self.dependencies["gflags"].cpp_info
        pb = self.dependencies["protobuf"].cpp_info
        ldb = self.dependencies["leveldb"].cpp_info
        ssl = self.dependencies["openssl"].cpp_info

        gf_inc = gf.includedirs[0] if gf.includedirs else ""
        pb_inc = pb.includedirs[0] if pb.includedirs else ""
        ldb_inc = ldb.includedirs[0] if ldb.includedirs else ""
        ssl_inc = ssl.includedirs[0] if ssl.includedirs else ""

        # Locate the protoc binary in the Conan protobuf package.
        protoc = ""
        for bindir in pb.bindirs:
            candidate = os.path.join(bindir, "protoc")
            if os.path.isfile(candidate):
                protoc = candidate.replace("\\", "/")
                break

        lines = [
            "",
            "# ---------------------------------------------------------------",
            "# brpc recipe: Conan dependency paths",
            "# Appended by BrpcConan.generate().",
            "# ---------------------------------------------------------------",
            "",
            "# -- Block Homebrew from all find_* commands --",
            "#",
            "# On macOS, /opt/homebrew is on the default search path for",
            "# find_path / find_library / find_package.  Since ALL deps come",
            "# from Conan (with paths CACHE-FORCE'd below), we tell CMake to",
            "# ignore Homebrew entirely.  This prevents stale Homebrew",
            "# libraries/headers from leaking in through any find_* call we",
            "# didn't anticipate.",
            'set(CMAKE_IGNORE_PATH "/opt/homebrew;/opt/homebrew/include;/opt/homebrew/lib" CACHE STRING "" FORCE)',
            'set(CMAKE_IGNORE_PREFIX_PATH "/opt/homebrew" CACHE STRING "" FORCE)',
            'set(CMAKE_SYSTEM_IGNORE_PATH "/opt/homebrew;/opt/homebrew/include;/opt/homebrew/lib" CACHE STRING "" FORCE)',
            'set(CMAKE_SYSTEM_IGNORE_PREFIX_PATH "/opt/homebrew" CACHE STRING "" FORCE)',
            "",
            "# -- Priority include directories --",
            "#",
            "# Prepend Conan include paths as -I flags (NOT -isystem).  The",
            "# SYSTEM keyword is intentionally omitted: -isystem paths are",
            "# always searched AFTER -I paths, so -isystem cannot override a",
            "# -I /opt/homebrew/include that leaks in from brpc's CMake code",
            "# or imported targets.  BEFORE ensures these come first in the",
            "# -I ordering, even before brpc's own include_directories() calls.",
        ]
        for inc in (pb_inc, gf_inc, ldb_inc, ssl_inc):
            if inc:
                lines.append(f'include_directories(BEFORE "{inc}")')
        lines.append("")

        # -- gflags --
        # brpc's cmake/FindGFLAGS.cmake uses find_path(GFLAGS_INCLUDE_PATH)
        # and find_library(GFLAGS_LIBRARY).  Pre-setting these in the cache
        # makes those calls no-ops.
        lines.append("# gflags")
        lines.append("# Note: Conan's gflags 2.2.2 ships as libgflags_nothreads.a,")
        lines.append("# not libgflags.a.  _find_lib resolves the actual filename.")
        lines.append(f'set(GFLAGS_INCLUDE_PATH "{gf_inc}" CACHE PATH "" FORCE)')
        gf_lib = self._find_lib(gf)
        lines.append(f'set(GFLAGS_LIBRARY "{gf_lib}" CACHE FILEPATH "" FORCE)')
        # GFLAGS_NS: brpc's CMakeLists.txt runs a bash grep on gflags
        # headers to auto-detect the namespace.  With gflags 2.2.2 it's
        # "gflags".  Pre-setting avoids the grep (which fails if bash or
        # the header is not where expected).
        lines.append('set(GFLAGS_NS "gflags" CACHE STRING "" FORCE)')
        lines.append("")

        # -- protobuf --
        # The shim FindProtobuf.cmake (written in source()) reads these
        # variables and declares Protobuf found without searching.
        # We set BOTH mixed-case (CMake convention) and upper-case (brpc's
        # CompileProto.cmake convention).
        #
        # Protobuf_DIR: highest-priority hint for config-mode find_package.
        # Points to the generators folder where ProtobufConfig.cmake lives.
        # This ensures find_package(Protobuf) in config mode (which runs
        # first due to CMAKE_FIND_PACKAGE_PREFER_CONFIG=ON) finds our shim
        # before Homebrew's /opt/homebrew/lib/cmake/protobuf/protobuf-config.cmake.
        lines.append("# protobuf (mixed-case = CMake, upper-case = brpc)")
        lines.append(
            f'set(Protobuf_DIR "{self.generators_folder}" CACHE PATH "" FORCE)'
        )
        pb_lib = self._find_lib(pb, "protobuf")
        pb_protoc_lib = self._find_lib(pb, "protoc")
        for var in ("Protobuf_INCLUDE_DIR", "PROTOBUF_INCLUDE_DIR"):
            lines.append(f'set({var} "{pb_inc}" CACHE PATH "" FORCE)')
        lines.append(f'set(PROTOBUF_INCLUDE_DIRS "{pb_inc}" CACHE PATH "" FORCE)')
        for var in ("Protobuf_LIBRARY", "PROTOBUF_LIBRARY"):
            lines.append(f'set({var} "{pb_lib}" CACHE FILEPATH "" FORCE)')
        lines.append(f'set(PROTOBUF_LIBRARIES "{pb_lib}" CACHE FILEPATH "" FORCE)')
        for var in ("Protobuf_PROTOC_LIBRARY", "PROTOBUF_PROTOC_LIBRARY"):
            lines.append(f'set({var} "{pb_protoc_lib}" CACHE FILEPATH "" FORCE)')
        for var in ("Protobuf_PROTOC_EXECUTABLE", "PROTOBUF_PROTOC_EXECUTABLE"):
            lines.append(f'set({var} "{protoc}" CACHE FILEPATH "" FORCE)')
        # PROTOC_LIB: brpc CMakeLists.txt line ~259 does
        #   find_library(PROTOC_LIB NAMES protoc)
        # and then links it into the brpc library.  Pre-setting prevents
        # find_library from picking up Homebrew's libprotoc.
        lines.append(f'set(PROTOC_LIB "{pb_protoc_lib}" CACHE FILEPATH "" FORCE)')
        lines.append("")

        # -- leveldb --
        # brpc uses find_path(LEVELDB_INCLUDE_PATH) and
        # find_library(LEVELDB_LIB).
        lines.append("# leveldb")
        lines.append(f'set(LEVELDB_INCLUDE_PATH "{ldb_inc}" CACHE PATH "" FORCE)')
        ldb_lib = self._find_lib(ldb)
        lines.append(f'set(LEVELDB_LIB "{ldb_lib}" CACHE FILEPATH "" FORCE)')
        lines.append("")

        # -- openssl --
        # brpc calls find_package(OpenSSL), which uses CMake's built-in
        # FindOpenSSL.  Unlike FindProtobuf, FindOpenSSL reliably respects
        # pre-set cache variables — no shim needed.
        lines.append("# openssl (FindOpenSSL respects cache — no shim needed)")
        lines.append(f'set(OPENSSL_INCLUDE_DIR "{ssl_inc}" CACHE PATH "" FORCE)')
        ssl_lib = self._find_lib(ssl, "ssl")
        crypto_lib = self._find_lib(ssl, "crypto")
        lines.append(f'set(OPENSSL_SSL_LIBRARY "{ssl_lib}" CACHE FILEPATH "" FORCE)')
        lines.append(
            f'set(OPENSSL_CRYPTO_LIBRARY "{crypto_lib}" CACHE FILEPATH "" FORCE)'
        )
        lines.append("")

        toolchain_path = os.path.join(self.generators_folder, "conan_toolchain.cmake")
        with open(toolchain_path, "a") as f:
            f.write("\n".join(lines) + "\n")

    def _patch_out_protoc_gen_mcpack(self):
        """Remove the protoc-gen-mcpack build target from brpc's CMake.

        protoc-gen-mcpack is a protobuf compiler plugin for brpc's mcpack
        serialization format.  QuorumKit does not use mcpack, so we don't
        need this binary.

        On Linux, protoc-gen-mcpack fails to link because brpc's
        DYNAMIC_LIB variable has incorrect static-library link order:
        zlib appears before OpenSSL, so when the GNU single-pass linker
        processes libcrypto.a and needs zlib symbols, they've already been
        discarded.  The macOS ld64 linker does multi-pass so this works
        locally but fails in CI (ubuntu-24.04).

        Rather than fixing the link order for a binary we don't need,
        we comment out all lines that reference the protoc-gen-mcpack
        target (plus any continuation lines of multi-line CMake commands).
        The brpc static library (brpc-static) builds and installs fine
        without it — there is no install() rule for protoc-gen-mcpack
        in brpc's src/CMakeLists.txt.
        """
        src_cmake = os.path.join(self.source_folder, "src", "CMakeLists.txt")

        with open(src_cmake) as f:
            content = f.read()

        # Comment out every line that references protoc-gen-mcpack or
        # protoc_gen_mcpack, plus continuation lines of multi-line CMake
        # commands.  A multi-line command is detected by counting parens:
        # if a matching line opens a '(' without a closing ')', we keep
        # commenting until the parens balance.
        patched_lines = []
        header_added = False
        in_multiline = False
        paren_depth = 0

        for line in content.splitlines(True):
            is_match = "protoc-gen-mcpack" in line or "protoc_gen_mcpack" in line

            if is_match or in_multiline:
                if not header_added:
                    patched_lines.append(
                        "# Patched out by QuorumKit brpc recipe — not needed, "
                        "fails to link on Linux.\n"
                    )
                    patched_lines.append(
                        "# See contrib/brpc/conanfile.py "
                        "_patch_out_protoc_gen_mcpack() for details.\n"
                    )
                    header_added = True
                patched_lines.append("# " + line)

                # Track paren depth for multi-line CMake commands.
                # Strip comments before counting (CMake # comments).
                code = line.split("#")[0] if not in_multiline else line
                paren_depth += code.count("(") - code.count(")")
                in_multiline = paren_depth > 0
            else:
                patched_lines.append(line)

        with open(src_cmake, "w") as f:
            f.writelines(patched_lines)

    def build(self):
        self._patch_out_protoc_gen_mcpack()
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.libs = ["brpc"]
        if self.settings.os in ["Linux", "FreeBSD"]:
            self.cpp_info.system_libs = ["dl", "rt", "pthread"]
        elif self.settings.os == "Macos":
            # brpc links CoreFoundation, Security, etc. on macOS.
            # Listing them here lets downstream consumers (QuorumKit's
            # CMakeLists.txt) pick them up automatically via
            # target_link_libraries transitivity.
            self.cpp_info.frameworks = [
                "CoreFoundation",
                "CoreGraphics",
                "CoreData",
                "CoreText",
                "Security",
                "Foundation",
            ]
            self.cpp_info.system_libs = ["pthread"]
        self.cpp_info.set_property("cmake_file_name", "brpc")
        self.cpp_info.set_property("cmake_target_name", "brpc::brpc")
